FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu
COPY requirements-base.txt .
RUN pip install --no-cache-dir -r requirements-base.txt && python -m spacy download en_core_web_sm
